---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fftlhqzd/public_html/
    - /bin/cp -R wp-content/plugins/art-cms ../../public_html/wp-content/plugins/
    - /bin/cp -R wp-content/plugins/contact-workflow ../../public_html/wp-content/plugins/
    - /bin/cp -R wp-content/plugins/site-mode ../../public_html/wp-content/plugins/
    - /bin/cp -R wp-content/plugins/welcome-screen ../../public_html/wp-content/plugins/
    - /bin/cp -R wp-content/themes/art-theme ../../public_html/wp-content/themes/
